[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100",  # Игнорируем warnings по отсутствию докстрингов, если не нужны
    "D104",
    "ANN101", # Игнорируем отсутствие аннотаций self
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
asyncio_mode = "auto"
