"""create users and payments tables

Revision ID: c51f3db7ebfb
Revises: 64e7081c7b3b
Create Date: 2025-04-07 16:17:19.108602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51f3db7ebfb'
down_revision: Union[str, None] = '64e7081c7b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_referrer_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_referrer_id_fkey', 'users', 'users', ['referrer_id'], ['user_id'])
    # ### end Alembic commands ###
